language: php
sudo: false

php:
  - 7.3
  - 7.4

install:
  - composer install --no-interaction

script:
  - ./bin/phpunit
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - composer validate